mongodb1:
  hostname: 'mongodb1'
  image: hpess/mongodb
  environment:
    - DEBUG=true
    - noprealloc=true
    - smallfiles=true
    - replSet=rs1
    - replMembers=172.17.42.1:27018,172.17.42.1:27019
  ports:
    - "172.17.42.1:27017:27017"
    - "28017:28017"

mongodb2:
  hostname: 'mongodb2'
  image: hpess/mongodb
  environment:  
    - DEBUG=true
    - noprealloc=true
    - smallfiles=true
    - replSet=rs1
  ports:
    - "172.17.42.1:27018:27017"
  links:
    - "mongodb1:mongodb1"

mongodb3:
  hostname: 'mongodb3'
  image: hpess/mongodb
  environment:
    - DEBUG=true
    - noprealloc=true
    - smallfiles=true
    - replSet=rs1
  ports:
    - "172.17.42.1:27019:27017"
  links:
    - "mongodb1:mongodb1"
